server:
  port: 8002


spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:8066/cloud?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  cloud:
    zookeeper:
      connect-string: 172.16.8.197:2181,172.16.8.197:2182,172.16.8.197:2183


mybatis:
  mapper-locations: classpath:mapper/*.xml
  #type-aliases-package: com.pandau.cloud.entities
