server:
  port: 10010
spring:
  application:
    name: seata-bus
  profiles:
    active: dev
  master:     ##主库
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3307/cloud?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
  slave:     ##从库
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3308/cloud?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: read
      password: 123456
management:
  endpoints:
    web:
      exposure:
        include: "*"
