server:
  port: 80


eureka:
  instance:
    #hostname: localhost
    instance-id: order80
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#spring:
#  application:
#    name: payment-service
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:8066/cloud?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: 123456
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
feign:
  hystrix:
    enabled: true
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
  #type-aliases-package: com.pandau.cloud.entities
spring:
  application:
    name: order_80
